
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 05 17:55:46 PKT 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int EE = 17;
  public static final int TIMES = 14;
  public static final int MOD = 16;
  public static final int AND = 24;
  public static final int INPUT = 6;
  public static final int LT = 21;
  public static final int NE = 18;
  public static final int ELSE = 8;
  public static final int PLUS = 12;
  public static final int RPAREN = 27;
  public static final int OR = 25;
  public static final int THEN = 9;
  public static final int WHILE = 11;
  public static final int NOT = 23;
  public static final int END = 3;
  public static final int TRUE = 30;
  public static final int VARIABLE = 29;
  public static final int IF = 4;
  public static final int LPAREN = 28;
  public static final int GT = 22;
  public static final int LE = 20;
  public static final int BEGIN = 2;
  public static final int DO = 10;
  public static final int NUMBER = 32;
  public static final int EOF = 0;
  public static final int DIVIDE = 15;
  public static final int FALSE = 31;
  public static final int GE = 19;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int ASSIGN = 26;
  public static final int OUTPUT = 7;
  public static final int VAR = 5;
  public static final int UMINUS = 33;

  /* non terminals */
  static final int stmts = 3;
  static final int stmt = 1;
  static final int expr = 2;
  static final int prog = 0;
  static final int block = 4;
}

